<a href="https://colab.research.google.com/github/ken14121/-_loadto-/blob/main/%E3%83%87%E3%83%BC%E3%82%BF%E8%A7%A3%E6%9E%901_0529.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "日付":["2026-05-01", "2026-05-02", "2026-05-03", "2026-05-04", "2026-05-05"],
    "天気":["晴れ", "曇り", "雨", "晴れ", "晴れ"],
    "大人":[1200, 950, 420, 1500, 1650],
    "子供":[450, 320, 110, 850, 980],
    "高校生":[300, 280, 90, 400, 420],
    "カップル":[600, 500, 210, 750, 800],
    "一人":[80, 95, 45, 70, 65]
}

#2.Pdのデータフレームに変換
df = pd.DataFrame(data)

# 3. 作成したデータ（表）の先頭を表示
df

           日付  天気    大人   子供  高校生  カップル  一人
0  2026-05-01  晴れ  1200  450  300   600  80
1  2026-05-02  曇り   950  320  280   500  95
2  2026-05-03   雨   420  110   90   210  45
3  2026-05-04  晴れ  1500  850  400   750  70
4  2026-05-05  晴れ  1650  980  420   800  65

In [ ]:
df.head(3)

           日付  天気    大人   子供  高校生  カップル  一人
0  2026-05-01  晴れ  1200  450  300   600  80
1  2026-05-02  曇り   950  320  280   500  95
2  2026-05-03   雨   420  110   90   210  45

In [ ]:
df.shape

(5, 7)

ｃとの差で聞きたいことがあって
なんでprint(df)じゃなくても表示できるの

理由②：Pandasが「綺麗なHTMLの表」を返すように設計されているから
ここが最も大きな違いである。実は、print(df) と書くこと自体は可能である。しかし、あえて print() を付けずに df だけ単体で実行しているのには理由がある。

print(df) と書いた場合:
Pythonの標準的なテキスト出力になり、黒い画面（C言語のコンソール）のような、文字だけの素朴な表が表示される。

df だけを書いた場合（推奨）:
PandasがGoogle Colabと連携し、Webブラウザで見やすいように「枠線や背景色がついた綺麗なHTMLの表」としてリッチに出力してくれる。

データサイエンスでは、データの並びや桁数をパッと見で綺麗に確認したいため、実務でも print(df) は使わず、セルの最後に df とだけ書いて綺麗な表を表示させるのが一般的になっている。

In [ ]:
print(df)

           日付  天気    大人   子供  高校生  カップル  一人
0  2026-05-01  晴れ  1200  450  300   600  80
1  2026-05-02  曇り   950  320  280   500  95
2  2026-05-03   雨   420  110   90   210  45
3  2026-05-04  晴れ  1500  850  400   750  70
4  2026-05-05  晴れ  1650  980  420   800  65

じゃあこれ逆に絞って3行3列だけ出力とかもできるの？

結論から言うと、完全にできる。 しかも、Pandasにはそのための「行と列を同時に指定して切り出す超強力な方法」が用意されている。C言語のようにループを回してインデックスを指定する必要はなく、指定の仕方も直感的である。

いくつか方法はあるが、実務で最も使われており、これだけ覚えておけば間違いないというloc（ロック）とiloc（アイロック）という方法を紹介する。

Google Colabの新しいセルで、以下のコードをそれぞれ試してみてほしい。

方法①：インデックスの「番号」で 3行 × 3列 を切り出す（iloc）
C言語の2次元配列の添字（matrix[i][j]）に一番近い感覚で、「0番目から数えて何行目・何列目か」の数字で指定する方法である。

Python
# 0〜2行目（3行分） と 0〜2列目（3列分）を切り出す
df.iloc[0:3, 0:3]
コードの解説
.iloc は「Integer Location（整数の位置）」の略である。

カンマ , を挟んで、左側が行の指定、右側が列の指定 になる。

0:3 はPythonのスライスという機能で、「0番目から、3番目の手前まで（つまり0, 1, 2）」 という意味になる。C言語の for (int i = 0; i < 3; i++) と同じ範囲の指定方法である。

方法②：列の「名前」で指定して切り出す（loc）
データサイエンスの実務では、「左から〇番目の列」と数字で数えるよりも、「『天気』と『大人』の列が欲しい」というように名前で指定することの方が圧倒的に多い。その場合は .loc を使う。

Python
# 0〜2行目（※3行分） と 「日付」「天気」「大人」の3列を切り出す
df.loc[0:2, ["日付", "天気", "大人"]]
コードの解説
.loc は「Location（位置・ラベル）」の略である。

列の指定部分（カンマの右側）に、["列名1", "列名2", "列名3"] のようにリスト形式で欲しい列の名前を直接書くことができる。

注意（C言語脳での落とし穴）： .loc で行を 0:2 と書いた場合、先ほどの .iloc と違って「2の手前まで」ではなく、「2番目の行も含める」 というルールになる。そのため、0, 1, 2の3行分が出力される。

In [ ]:
# 0〜2行目（3行分） と 0〜2列目（3列分）を切り出す
df.iloc[0:3, 0:3]

           日付  天気    大人
0  2026-05-01  晴れ  1200
1  2026-05-02  曇り   950
2  2026-05-03   雨   420

In [ ]:
# 0〜2行目（※3行分） と 「日付」「天気」「大人」の3列を切り出す
df.loc[0:2, ["日付", "天気", "大人"]]#.loc はLocation位置・ラベルの略で

           日付  天気    大人
0  2026-05-01  晴れ  1200
1  2026-05-02  曇り   950
2  2026-05-03   雨   420

In [ ]:
# 1. 新しい列「総客数」を作り、大人・子供・高校生の数をすべて足し算して格納する
df["総客数"] = df["大人"] + df["子供"] + df["高校生"]

# 2. 列が増えたデータフレーム（表）全体をもう一度表示して確認
df

           日付  天気    大人   子供  高校生  カップル  一人   総客数
0  2026-05-01  晴れ  1200  450  300   600  80  1950
1  2026-05-02  曇り   950  320  280   500  95  1550
2  2026-05-03   雨   420  110   90   210  45   620
3  2026-05-04  晴れ  1500  850  400   750  70  2750
4  2026-05-05  晴れ  1650  980  420   800  65  3050