<a href="https://colab.research.google.com/github/ken14121/-_loadto-/blob/main/%E3%83%87%E3%83%BC%E3%82%BF%E8%A7%A3%E6%9E%904_0612.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "大人": [1200, 950, 420, 1500, 1650],
    "子供": [450, 320, 110, 850, 980],
    "天気": ["晴れ", "曇り", "雨", "晴れ", "晴れ"],
    "総客数": [1950, 1550, 620, 2750, 3050]
})

df

     大人   子供  天気   総客数
0  1200  450  晴れ  1950
1   950  320  曇り  1550
2   420  110   雨   620
3  1500  850  晴れ  2750
4  1650  980  晴れ  3050

In [ ]:
X = pd.get_dummies(df[["大人", "子供", "天気"]], drop_first=True)
y = df["総客数"]

X

     大人   子供  天気_曇り   天気_雨
0  1200  450  False  False
1   950  320   True  False
2   420  110  False   True
3  1500  850  False  False
4  1650  980  False  False

元データが

晴れ

曇り

雨

なら、変換後のイメージ。

   天気_曇り  天気_雨
0       0      0   # 晴れ
1       1      0   # 曇り
2       0      1   # 雨

ここで 晴れ が消えているのは、drop_first=True を付けているから。

なんで1つ落とすのか
理由は、全部の列を残すと情報がかぶるから です。

たとえば 晴れ, 曇り, 雨 の3列を全部残すと、

3列のうち2列が分かれば、残り1列は自動的に分かる
という状態になります。
これは重回帰では「同じ情報を二重に持っている」ことになって、計算が不安定になりやすいです。

なので、1つ基準を落とします。
今回なら 晴れ を基準にしていて、

天気_曇り = 1 なら曇り
天気_雨 = 1 なら雨
どちらも 0 なら晴れ
という読み方になります。

つまり、drop_first=True で落ちたのは 晴れ です。

「どこから曇りと雨は来たの？」
これは df["天気"] の中に もともと入っている値 です。
get_dummies() は、その列に登場した文字を自動で見つけて、列に展開します。

たとえばこのデータなら、

df["天気"]
の中身が

晴れ
曇り
雨
なので、get_dummies() がそれを見て自動で列を作ります。

つまり、曇りと雨はどこかから持ってきたのではなく、元の df に入っていた値から自動生成された ものです。

Pythonの get_dummies() は、その変換を自動でやってくれる道具です。
だから「天気の列を見て、必要なダミー列を勝手に作る」という理解で大丈夫です。

まずは覚えるポイント
get_dummies() = 文字を0/1列に変える
drop_first=True = 1列落として重複情報を避ける
落ちる列は、先頭のカテゴリ
今回は 晴れ が基準になった
曇り と 雨 は、元の df["天気"] から自動で作られた

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)

print("係数:", model.coef_)
print("切片:", model.intercept_)

係数: [   0.76190476    1.42857143  -23.80952381 -250.        ]
切片: 392.85714285714175

In [ ]:
pred = model.predict(X)
df["予測値"] = pred
df["誤差"] = df["総客数"] - df["予測値"]
df

     大人   子供  天気   総客数     予測値            誤差
0  1200  450  晴れ  1950  1950.0 -4.547474e-13
1   950  320  曇り  1550  1550.0  0.000000e+00
2   420  110   雨   620   620.0  0.000000e+00
3  1500  850  晴れ  2750  2750.0  4.547474e-13
4  1650  980  晴れ  3050  3050.0  4.547474e-13

In [ ]:
df["誤差"].abs().mean()

np.float64(2.7284841053187846e-13)

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({
    "大人": [1200, 950, 420, 1500, 1650],
    "子供": [450, 320, 110, 850, 980],
    "天気": ["晴れ", "曇り", "雨", "晴れ", "晴れ"],
    "総客数": [1950, 1550, 620, 2750, 3050]
})

X = pd.get_dummies(df[["大人", "子供", "天気"]], drop_first=True)
y = df["総客数"]

X

     大人   子供  天気_曇り   天気_雨
0  1200  450  False  False
1   950  320   True  False
2   420  110  False   True
3  1500  850  False  False
4  1650  980  False  False

In [ ]:
model = LinearRegression()
model.fit(X, y)

print("係数:", model.coef_)
print("切片:", model.intercept_)

係数: [   0.76190476    1.42857143  -23.80952381 -250.        ]
切片: 392.85714285714175

In [ ]:
pred = model.predict(X)

df["予測値"] = pred
df["誤差"] = df["総客数"] - df["予測値"]
df

     大人   子供  天気   総客数     予測値            誤差
0  1200  450  晴れ  1950  1950.0 -4.547474e-13
1   950  320  曇り  1550  1550.0  0.000000e+00
2   420  110   雨   620   620.0  0.000000e+00
3  1500  850  晴れ  2750  2750.0  4.547474e-13
4  1650  980  晴れ  3050  3050.0  4.547474e-13

In [ ]:
df["誤差"].abs().mean()

np.float64(2.7284841053187846e-13)

np.float64(3.1832314562052486e-13) は、ほぼ 0 です。

つまり今回のデータでは、

予測値と実測値がほぼ一致している
誤差は実質ゼロ
ということです。

この e-13 は、コンピュータの小数計算の誤差みたいなものです。
人間の感覚では 0 と見て問題ありません。

In [ ]:
print(X.columns)
print(model.coef_)
print(model.intercept_)

Index(['大人', '子供', '天気_曇り', '天気_雨'], dtype='object')
[   0.76190476    1.42857143  -23.80952381 -250.        ]
392.85714285714175

「大人1200人、子供400人、天気は雨」のような1件を作って、predict() で出してみる。

In [ ]:
new_data = pd.DataFrame({
    "大人": [1200],
    "子供": [400],
    "天気": ["雨"]
})

new_X = pd.get_dummies(new_data, drop_first=True)
new_X

     大人   子供
0  1200  400

In [ ]:
new_X = new_X.reindex(columns=X.columns, fill_value=0)
new_X

     大人   子供  天気_曇り  天気_雨
0  1200  400      0     0

In [ ]:
model.predict(new_X)

array([1878.57142857])

In [ ]:
new_data = pd.DataFrame({
    "大人": [1200],
    "子供": [400],
    "天気": ["雨"]
})

new_X = pd.get_dummies(new_data, drop_first=True)
new_X = new_X.reindex(columns=X.columns, fill_value=0)

pred = model.predict(new_X)
pred

array([1878.57142857])

重回帰を、講義資料っぽい実データで進める。
まずは student-math.csv を使う形で始めるのが自然です。Colab なら、まずこの形で読み込む
。

In [ ]:
import pandas as pd

df = pd.read_csv("student-mat.csv", sep=";")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

ここは、どの列を説明変数に使えそうか。
重回帰なら、最初はこんな感じで考える。

studytime

failures

absences

G1

G2

目的変数は G3 にすることが多い。

これは「最終成績を、途中の成績や学習量から予測する」形\。

まずは数値列だけを使って、シンプルに。

In [ ]:
X = df[["studytime", "failures", "absences", "G1", "G2"]]
y = df["G3"]

X.head(), y.head()

(   studytime  failures  absences  G1  G2
 0          2         0         6   5   6
 1          2         0         4   5   5
 2          2         3        10   7   8
 3          3         0         2  15  14
 4          2         0         4   6  10,
 0     6
 1     6
 2    10
 3    15
 4    10
 Name: G3, dtype: int64)

(X.head(), y.head())
みたいに書くと、Pythonは2つのものをセットで返すので、見た目がこうなります。

(

  Xの先頭5行,

  yの先頭5件

)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)

print("係数:", model.coef_)
print("切片:", model.intercept_)

係数: [-0.1781672  -0.28377282  0.03663799  0.14996393  0.9772637 ]
切片: -1.4427564095826657

In [ ]:
X.columns

Index(['studytime', 'failures', 'absences', 'G1', 'G2'], dtype='object')

In [ ]:
pred = model.predict(X)
df["予測G3"] = pred
df["誤差"] = df["G3"] - df["予測G3"]
df[["G3", "予測G3", "誤差"]].head()

   G3       予測G3        誤差
0   6   5.034139  0.965861
1   6   3.983599  2.016401
2  10   6.583828  3.416172
3  15  14.027169  0.972831
4  10   9.019882  0.980118

## pred = model.predict(X)

これは、学習済みモデルに X を入れて、予測値を出している行です。

pred には、G3 の予測結果が入ります。

次の行で、予測値を df に追加しています。

## df["予測G3"] = pred

つまり、もともとの表に 予測G3 という新しい列を足しています。

その次は誤差です。

## df["誤差"] = df["G3"] - df["予測G3"]

これは
実測値 G3
予測値 予測G3
の差を取っているだけです。
最後に、見やすく抜き出しています。

## df[["G3", "予測G3", "誤差"]].head()

これは
実測値
予測値
誤差
だけを見ている、ということです。

なんで式を自分で作らずに計算できるのか
ここがいちばん本質で、モデルがデータから式を学習した結果。たとえば重回帰は、内部でこういう形の式を作っています。

G3 = a1 * studytime + a2 * failures + a3 * absences + a4 * G1 + a5 * G2 + b

この

a1, a2, a3, a4, a5

b

を、fit(X, y) がデータから自動で決めています。
だから、自分で式を毎回書かなくても、

# model.predict(X)

とするだけで、モデルが内部で持っている式を使って計算してくれます。

In [ ]:
df["誤差"].abs().mean()

np.float64(1.1552143708227982)

In [ ]:
print(X.columns)
print(model.coef_)
print(model.intercept_)

Index(['studytime', 'failures', 'absences', 'G1', 'G2'], dtype='object')
[-0.1781672  -0.28377282  0.03663799  0.14996393  0.9772637 ]
-1.4427564095826657

In [ ]:
pred = model.predict(X)

df["予測G3"] = pred
df["誤差"] = df["G3"] - df["予測G3"]

df[["G3", "予測G3", "誤差"]].head()

   G3       予測G3        誤差
0   6   5.034139  0.965861
1   6   3.983599  2.016401
2  10   6.583828  3.416172
3  15  14.027169  0.972831
4  10   9.019882  0.980118

In [ ]:
df["誤差"].abs().mean()

np.float64(1.1552143708227982)